name: Run Daily Script

on:
  schedule:
    - cron: '39 0 * * *' # Runs at 0:36 AM UTC, which is 2:36 AM EET

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Run script
      run: node theatro.mjs
